name: QA

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  QA:
    runs-on: ubuntu-latest

    steps:
      - name: Setup credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y clang libclang-dev libopencv-dev

      - name: Set nightly
        run: rustup default nightly

      - name: Build
        run: cargo check --verbose
